on: 
 workflow_dispatch:
jobs:
 example:
  runs-on: ubuntu-latest
  steps:
  - name: check if file exist
    run: |
      if [-f "config.yml"]; then
        echo "::debug::config.yml exist"
      else
        echo "::error:: config.yml not exist"
      
    
   
  
