name: first workflow

on:  
  push:
     branches: 
     - main

jobs:
  example-job:
         runs-on: ubuntu-latest

         steps:
           - name: print welcome message
             run: echo "welcome to first github action workflow" 

           - name: checkout
             uses: actions/checkout@v6.0.3 
             
           - name: list repo files
             run: ls -la
    
